name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script_stop: true
        script: |
          set -e

          # Vérifier les versions de Node.js et npm
          echo "Node.js version: $(node -v)"
          echo "npm version: $(npm -v)"

          cd /var/www
          rm -rf ./Book
          
          # Cloner le dépôt
          git clone https://github.com/eliooooooo/Book.git

          # Afficher les fichiers et permissions dans le répertoire www avant l'installation
          echo "Contenu du répertoire www avant l'installation:"
          cd Book
          ls -l
          
          # Installer les dépendances
          npm ci
          
          # Afficher les fichiers et permissions dans le répertoire www après l'installation
          echo "Contenu du répertoire www après l'installation:"
          ls -l

          # Exécuter npm run prod et capturer les erreurs
          echo "Exécution de npm run prod:"
          npm run prod 2>error.log || { echo 'npm run prod failed'; cat error.log; exit 1; }
