name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        script_stop: true
        script: |
          set -e # Arrêter le script si une commande échoue
          git clone https://github.com/eliooooooo/Book.git
          if [ ! -d "www" ]; then
            mkdir www
          fi
          cp -r Book/* www
          rm -rf Book
          cd www
          npm install
          npm run prod || { echo 'npm run prod failed'; exit 1; }
